config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  resources :discounts
  resources :societies
  devise_for :users
  resources :categories
  root 'categories#index'

end

app/models/society.rb
class Society < ActiveRecord::Base
  has_many :discounts
  has_many :categories, through: :discounts

  accepts_nested_attributes_for :discounts,reject_if: :all_blank,allow_destroy: true
end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
  before_action :set_society, only: [:show, :edit, :update, :destroy]

  # GET /societies
  # GET /societies.json
  def index
    @societies = Society.all
  end

  # GET /societies/1
  # GET /societies/1.json
  def show
  end

  # GET /societies/new
  def new
    @society = Society.new
  end

  # GET /societies/1/edit
  def edit
  end

  # POST /societies
  # POST /societies.json
  def create
    @society = Society.new(society_params)

    respond_to do |format|
      if @society.save
        format.html { redirect_to @society, notice: 'Society was successfully created.' }
        format.json { render :show, status: :created, location: @society }
      else
        format.html { render :new }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /societies/1
  # PATCH/PUT /societies/1.json
  def update
    respond_to do |format|
      if @society.update(society_params)
        format.html { redirect_to @society, notice: 'Society was successfully updated.' }
        format.json { render :show, status: :ok, location: @society }
      else
        format.html { render :edit }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /societies/1
  # DELETE /societies/1.json
  def destroy
    @society.destroy
    respond_to do |format|
      format.html { redirect_to societies_url, notice: 'Society was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_society
      @society = Society.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def society_params
      params.require(:society).permit(:nombre, :descripcion, :valor_anual, :valor_semestral, :valor_mensual,
                                      :discounts_attributes => [:id, :porcentaje_descuento, :society_id, :category_id, :_destroy,
                                                                :category_attributes => [:id, :nombre]] )
    end
end

app/helpers/societies_helper.rb
module SocietiesHelper
end

app/views/societies/_discount_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <table width="500" >
      <tr>
        <td><%= f.collection_select :category_id, Category.order(:nombre), :id, :nombre, include_blank: true%></td>
        <td> <%= f.number_field :porcentaje_descuento %>
          <%=link_to_remove_association "Eliminar", f %></td>
      </tr>
    </table>
  </div>
</li>

app/views/societies/_form.html.erb
<%= form_for(@society) do |f| %>
  <% if @society.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@society.errors.count, "error") %> prohibited this society from being saved:</h2>

      <ul>
      <% @society.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre,autofocus: true, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :descripcio %><br>
    <%= f.text_area :descripcio,autofocus: true, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :valor_anual %><br>
    <%= f.text_field :valor_anual,autofocus: true, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :valor_semestral %><br>
    <%= f.text_field :valor_semestral,autofocus: true, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :valor_mensual %><br>
    <%= f.text_field :valor_mensual,autofocus: true, class: 'form-control' %>
  </div>

  <div align="center">
      <%= link_to_add_association 'Añadir descuento', f,:discounts,
                                  'data-association-insertion-node' => "#discounts-category ",
                                  'data-association-insertion-method' => "append",
                                    :wrap_object => Proc.new {|discount| discount.build_category; discount }%>
      <hr/>
      <fieldset id="discounts-category">
        <%= f.fields_for :discounts do |discount| %>
            <%= render partial: "discount_fields", locals: {f:discount} %>
        <%end%>
      </fieldset>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/societies/edit.html.erb
<h1>Editing Society</h1>

<%= render 'form' %>

<%= link_to 'Show', @society %> |
<%= link_to 'Back', societies_path %>

app/views/societies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Societies</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Valor anual</th>
      <th>Valor semestral</th>
      <th>Valor mensual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @societies.each do |society| %>
      <tr>
        <td><%= society.nombre %></td>
        <td><%= society.descripcio %></td>
        <td><%= society.valor_anual %></td>
        <td><%= society.valor_semestral %></td>
        <td><%= society.valor_mensual %></td>
        <td><%= link_to 'Show', society %></td>
        <td><%= link_to 'Edit', edit_society_path(society) %></td>
        <td><%= link_to 'Destroy', society, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to "<i class='fa fa-plus-circle'></i> Nueva categoria".html_safe,
              new_society_path, class: 'btn btn-primary btn-lg'%>

app/views/societies/new.html.erb
<h1>New Society</h1>

<%= render 'form' %>

<%= link_to 'Back', societies_path %>

app/views/societies/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @society.nombre %>
</p>

<p>
  <strong>Descripcio:</strong>
  <%= @society.descripcio %>
</p>

<p>
  <strong>Valor anual:</strong>
  <%= @society.valor_anual %>
</p>

<p>
  <strong>Valor semestral:</strong>
  <%= @society.valor_semestral %>
</p>

<p>
  <strong>Valor mensual:</strong>
  <%= @society.valor_mensual %>
</p>

<%= link_to 'Edit', edit_society_path(@society) %> |
<%= link_to 'Back', societies_path %>