config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  resources :discounts
  resources :societies
  devise_for :users
  resources :categories
  root 'categories#index'

end

app/models/discount.rb
class Discount < ActiveRecord::Base
  belongs_to :society
  belongs_to :category
  accepts_nested_attributes_for :category, reject_if: :all_blank,allow_destroy: true
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  # GET /discounts
  # GET /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1
  # GET /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  # POST /discounts
  # POST /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to @discount, notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1
  # PATCH/PUT /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to @discount, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1
  # DELETE /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_params
      params.require(:discount).permit(:porcentaje_descuento)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.erb
<%= form_for(@discount) do |f| %>
  <% if @discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
      <% @discount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :porcentaje_descuento %><br>
    <%= f.number_field :porcentaje_descuento , autofocus: true, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing Discount</h1>

<%= render 'form' %>

<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>

app/views/discounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Discounts</h1>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Porcentaje descuento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounts.each do |discount| %>
      <tr>
        <td><%= discount.porcentaje_descuento %></td>
        <td><%= link_to 'Show', discount %></td>
        <td><%= link_to 'Edit', edit_discount_path(discount) %></td>
        <td><%= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<i class='fa fa-plus-circle'></i> Nueva descuento".html_safe,
              new_discount_path, class: 'btn btn-primary btn-lg'%>

app/views/discounts/new.html.erb
<h1>New Discount</h1>

<%= render 'form' %>

<%= link_to 'Back', discounts_path %>

app/views/discounts/show.html.erb
<p>
  <strong>Porcentaje descuento:</strong>
  <%= @discount.porcentaje_descuento %>
</p>

<%= link_to 'Edit', edit_discount_path(@discount) %> |
<%= link_to 'Back', discounts_path %>