config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  resources :discounts
  resources :societies
  devise_for :users
  resources :categories
  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :discounts
  has_many :societies, through: :discounts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource 
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end
  
  def search
   @categories = Category.search(params[:search_param])
      if @categories
      render partial: 'categories/lookup'
      else
      render status: :not_found, nothing: true
      end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nombre, :descripcion)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, autofocus: true, class: 'form-control' %>
  </div>
  
  
  <div class="form-group">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion, autofocus: true, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/_lookup.html.erb
<div id="friend-lookup">
    <h3>Busqueda categorias</h3>
    <%= form_tag search_categories_path, remote: true, method: :get, id: 'category-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-10">
            <%= text_field_tag :search_param,
            params[:search_param],
            placeholder: 'Nombre de la categoria',
            autofocus: true,
            class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
        <i class='fa fa-search'></i> Buscar categoria
        <% end %>
        </div>
    </div>
    <% end %>
    <% if @categories %>
        <% if @categories.size > 0 %>
            <h3>Buscar resultados</h3>
            <div id="category-lookup-results" class="well results-block col-md-10">
            <table class="search-results-table col-md-12">
            <tbody>
            <% @categories.each do |category| %>
                <tr>
                <td><strong>Name:</strong> <%= category.nombre %></td>
                <td><strong>Email:</strong> <%= category.descripcion %></td>
    </tr>
<% end %>
</tbody>
</table>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.nombre %></td>
        <td><%= category.descripcion %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "<i class='fa fa-plus-circle'></i> Nueva categoria".html_safe,
              new_category_path, class: 'btn btn-primary btn-lg'%>
      

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @category.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @category.descripcion %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>